core/urls.py
from django.urls import path

from core import views

app_name = 'core'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('categories/<int:pk>/products/', views.ProductListView.as_view(), name='product_list'),
    path('products/<int:pk>/', views.ProductDetailView.as_view(), name='product_detail'),
    path('products/<int:pk>/review/', views.ProductReviewView.as_view(), name='product_review'),
    path('cart/', views.CartView.as_view(), name='cart'),
    path('cart/add/', views.CartAddView.as_view(), name='cart_add'),
    path('cart/<int:pk>/update/', views.CartUpdateView.as_view(), name='cart_update'),
    path('cart/delete/', views.CartDeleteView.as_view(), name='cart_delete'),
    path('favorite/', views.FavoriteView.as_view(), name='favorite'),
    path('favorite/add/', views.FavoriteAddDeleteView.as_view(), name='favorite_add_delete'),
    path('favorite/delete/', views.FavoriteDeleteView.as_view(), name='favorite_delete'),
    path('mypage/', views.MyPageView.as_view(), name='mypage'),
    path('mypage/profile/update/', views.ProfileUpdateView.as_view(), name='profile_update'),
    path('mypage/credit_card/create', views.CreditCardCreateView.as_view(), name='credit_card_create'),
    path('mypage/address/update/', views.AddressUpdateView.as_view(), name='address_update'),
    path('mypage/user/delete/', views.UserDeleteView.as_view(), name='user_delete'),
    path('search/', views.SearchView.as_view(), name='search'),
    path('payment/', views.PaymentView.as_view(), name='payment')
]

samazon/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('samazon_admin/', include('samazon_admin.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

samazon_admin/urls.py
from django.urls import path

from samazon_admin import views

app_name = 'samazon_admin'
urlpatterns = [
    # viewsディレクトリの__init__.pyにfrom .home import *を記述しておくことで、views.HomeViewを参照することができる。
    path('', views.HomeView.as_view(), name='home'),

    path('major_categories/', views.MajorCategoryListView.as_view(), name='major_category_list'),
    path('major_categories/create/', views.MajorCategoryCreateView.as_view(), name='major_category_create'),
    path('major_categories/<int:pk>/', views.MajorCategoryDetailView.as_view(), name='major_category_detail'),
    path('major_categories/<int:pk>/update/', views.MajorCategoryUpdateView.as_view(), name='major_category_update'),
    path('major_categories/<int:pk>/delete/', views.MajorCategoryDeleteView.as_view(), name='major_category_delete'),

    path('categories/', views.CategoryListView.as_view(), name='category_list'),
    path('categories/create/', views.CategoryCreateView.as_view(), name='category_create'),
    path('categories/<int:pk>/', views.CategoryDetailView.as_view(), name='category_detail'),
    path('categories/<int:pk>/update/', views.CategoryUpdateView.as_view(), name='category_update'),
    path('categories/<int:pk>/delete/', views.CategoryDeleteView.as_view(), name='category_delete'),

    path('products/', views.ProductListView.as_view(), name='product_list'),
    path('products/create/', views.ProductCreateView.as_view(), name='product_create'),
    path('products/<int:pk>/', views.ProductDetailView.as_view(), name='product_detail'),
    path('products/<int:pk>/update/', views.ProductUpdateView.as_view(), name='product_update'),
    path('products/<int:pk>/delete/', views.ProductDeleteView.as_view(), name='product_delete'),

    path('users/', views.UserListView.as_view(), name='user_list'),
    path('users/<int:pk>/delete_revive', views.UserDeleteReviveView.as_view(), name='user_delete_revive'),
]

samazon_admin/models.py
from django.db import models

# Create your models here.

samazon_admin/forms.py
from django import forms

from core.models import Category, MajorCategory, Product


class MajorCategoryCreateUpdateForm(forms.ModelForm):
    class Meta:
        model = MajorCategory
        fields = '__all__'


class CategoryCreateUpdateForm(forms.ModelForm):
    major_category = forms.ModelChoiceField(queryset=MajorCategory.objects.all())

    class Meta:
        model = Category
        fields = '__all__'


class ProductCreateUpdateForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        categories = {'': '---------'}
        for category in Category.objects.all():
            categories.setdefault(category.major_category.name, [])
            categories[category.major_category.name].append([category.id, category.name])
        self.fields['category'].choices = categories.items()

core/views/product.py
from django.shortcuts import redirect, render
from django.views.generic import View

from core.models import Category, Product
from core.views.mixins import CategoryMixin, PaginationMixin


class ProductListView(CategoryMixin, PaginationMixin, View):
    def get(self, request, *args, **kwargs):
        category = Category.objects.get(pk=kwargs['pk'])
        # URLにorder_byパラメータがない場合は、idの昇順で並び替える
        products = category.products.all().order_by(request.GET.get('order_by', 'id'))
        context = {
            'category': category,
            'categories': self.get_categories(),  # 継承しているCategoryMixinのget_categoriesメソッドを実行
            **self.get_page_data(products)  # 継承しているPaginationMixinのget_page_dataメソッドを実行
        }
        return render(request, 'core/product/list.html', context)


class ProductDetailView(CategoryMixin, PaginationMixin, View):
    paginate_by = 2

    def get(self, request, *args, **kwargs):
        product = Product.objects.get(pk=kwargs['pk'])
        favorite_added = request.user.is_authenticated and request.user.favorites.filter(product=product).exists()
        context = {
            'product': product,
            'categories': self.get_categories(),  # 継承しているCategoryMixinのget_categoriesメソッドを実行
            'favorite_added': favorite_added,
            **self.get_page_data(product.reviews.all()),  # 継承しているPaginationMixinのget_page_dataメソッドを実行
        }
        return render(request, 'core/product/detail.html', context)


class ProductReviewView(View):
    def post(self, request, *args, **kwargs):
        product = Product.objects.get(pk=kwargs['pk'])
        product.reviews.create(
            user=request.user,
            score=request.POST['score'],
            body=request.POST['body']
        )
        return redirect('core:product_detail', product.pk)

samazon_admin/views/category.py
from django.shortcuts import redirect, render
from django.views.generic import View

from core.models import Category
from samazon_admin.forms import CategoryCreateUpdateForm


class CategoryListView(View):
    def get(self, request, *args, **kwargs):
        categories = Category.objects.all()
        return render(request, 'samazon_admin/category/list.html', {'categories': categories})


class CategoryCreateView(View):
    def get(self, request, *args, **kwargs):
        form = CategoryCreateUpdateForm()
        return render(request, 'samazon_admin/category/create.html', {'form': form})

    def post(self, request, *args, **kwargs):
        form = CategoryCreateUpdateForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('samazon_admin:category_list')
        return render(request, 'samazon_admin/category/create.html', {'form': form})


class CategoryDetailView(View):
    def get(self, request, *args, **kwargs):
        category = Category.objects.get(pk=kwargs['pk'])
        return render(request, 'samazon_admin/category/detail.html', {'category': category})


class CategoryUpdateView(View):
    def get(self, request, *args, **kwargs):
        category = Category.objects.get(pk=kwargs['pk'])
        form = CategoryCreateUpdateForm(instance=category)
        return render(request, 'samazon_admin/category/update.html', {'form': form})

    def post(self, request, *args, **kwargs):
        category = Category.objects.get(pk=kwargs['pk'])
        form = CategoryCreateUpdateForm(request.POST, instance=category)
        if form.is_valid():
            form.save()
            return redirect('samazon_admin:category_list')
        return render(request, 'samazon_admin/category/update.html', {'form': form})


class CategoryDeleteView(View):
    def post(self, request, *args, **kwargs):
        category = Category.objects.get(pk=kwargs['pk'])
        category.delete()
        return redirect('samazon_admin:category_list')

samazon_admin/views/home.py
from django.shortcuts import redirect
from django.views.generic import View


class HomeView(View):
    def get(self, request, *args, **kwargs):
        return redirect('samazon_admin:category_list')

samazon_admin/views/major_category.py
from django.shortcuts import redirect, render
from django.views.generic import View

from core.models import MajorCategory
from samazon_admin.forms import MajorCategoryCreateUpdateForm


class MajorCategoryListView(View):
    def get(self, request, *args, **kwargs):
        major_categories = MajorCategory.objects.all()
        return render(request, 'samazon_admin/major_category/list.html', {'major_categories': major_categories})


class MajorCategoryCreateView(View):
    def get(self, request, *args, **kwargs):
        form = MajorCategoryCreateUpdateForm()
        return render(request, 'samazon_admin/major_category/create.html', {'form': form})

    def post(self, request, *args, **kwargs):
        form = MajorCategoryCreateUpdateForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('samazon_admin:major_category_list')
        return render(request, 'samazon_admin/major_category/create.html', {'form': form})


class MajorCategoryDetailView(View):
    def get(self, request, *args, **kwargs):
        major_category = MajorCategory.objects.get(pk=kwargs['pk'])
        return render(request, 'samazon_admin/major_category/detail.html', {'major_category': major_category})


class MajorCategoryUpdateView(View):
    def get(self, request, *args, **kwargs):
        major_category = MajorCategory.objects.get(pk=kwargs['pk'])
        form = MajorCategoryCreateUpdateForm(instance=major_category)
        return render(request, 'samazon_admin/major_category/update.html', {'form': form})

    def post(self, request, *args, **kwargs):
        major_category = MajorCategory.objects.get(pk=kwargs['pk'])
        form = MajorCategoryCreateUpdateForm(request.POST, instance=major_category)
        if form.is_valid():
            form.save()
            return redirect('samazon_admin:major_category_list')
        return render(request, 'samazon_admin/major_category/update.html', {'form': form})


class MajorCategoryDeleteView(View):
    def post(self, request, *args, **kwargs):
        major_category = MajorCategory.objects.get(pk=kwargs['pk'])
        major_category.delete()
        return redirect('samazon_admin:major_category_list')

samazon_admin/views/product.py
from django.shortcuts import redirect, render
from django.views.generic import View

from core.models import Product
from core.views.mixins import PaginationMixin
from samazon_admin.forms import ProductCreateUpdateForm


class ProductListView(PaginationMixin, View):
    def get(self, request, *args, **kwargs):
        products = Product.objects.all()
        if 'keyword' in request.GET:
            products = products.filter(name__contains=request.GET['keyword'])
        products = products.order_by(request.GET.get('order_by', 'pk'))
        context = self.get_page_data(products)
        return render(request, 'samazon_admin/product/list.html', context)


class ProductCreateView(View):
    def get(self, request, *args, **kwargs):
        form = ProductCreateUpdateForm()
        return render(request, 'samazon_admin/product/create.html', {'form': form})

    def post(self, request, *args, **kwargs):
        # request.FILESにブラウザから送られてきた画像が入っている
        form = ProductCreateUpdateForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('samazon_admin:product_list')
        return render(request, 'samazon_admin/product/create.html', {'form': form})


class ProductDetailView(View):
    def get(self, request, *args, **kwargs):
        product = Product.objects.get(pk=kwargs['pk'])
        return render(request, 'samazon_admin/product/detail.html', {'product': product})


class ProductUpdateView(View):
    def get(self, request, *args, **kwargs):
        product = Product.objects.get(pk=kwargs['pk'])
        form = ProductCreateUpdateForm(instance=product)
        return render(request, 'samazon_admin/product/update.html', {'form': form})

    def post(self, request, *args, **kwargs):
        product = Product.objects.get(pk=kwargs['pk'])
        # request.FILESにブラウザから送られてきた画像が入っている
        form = ProductCreateUpdateForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            form.save()
            return redirect('samazon_admin:product_list')
        return render(request, 'samazon_admin/product/update.html', {'form': form})


class ProductDeleteView(View):
    def post(self, request, *args, **kwargs):
        product = Product.objects.get(pk=kwargs['pk'])
        product.delete()
        return redirect('samazon_admin:product_list')

samazon_admin/views/user.py
from datetime import datetime

from django.db.models import Q
from django.shortcuts import redirect, render
from django.views.generic import View

from core.models import User
from core.views.mixins import PaginationMixin


class UserListView(PaginationMixin, View):
    def get(self, request, *args, **kwargs):
        users = User.objects.all()
        if 'keyword' in request.GET:
            q = Q()
            for field_name in ('username', 'email', 'phone', 'postal_code', 'address'):
                q |= Q(**{f'{field_name}__contains': request.GET['keyword']})
            users = users.filter(q)
        context = self.get_page_data(users)
        return render(request, 'samazon_admin/user/list.html', context)


class UserDeleteReviveView(View):
    def post(self, request, *args, **kwargs):
        user = User.objects.get(pk=kwargs['pk'])
        User.objects.filter(pk=kwargs['pk']).update(deleted_at=datetime.now() if not user.deleted_at else None)
        return redirect('samazon_admin:user_list')

samazon_admin/templates/samazon_admin/product/create.html
{% extends 'samazon_admin/base.html' %}

{% block content %}
  <!-- 画像を送信するために、enctype="multipart/form-data"を使用 -->
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}

    <table>
      <tr>
        <th>画像</th><td>{{ form.photo }}</td>
      </tr>
      <tr>
        <th>カテゴリー</th><td>{{ form.category }}</td>
      </tr>
      <tr>
        <th>商品名</th><td>{{ form.name }}</td>
      </tr>
      <tr>
        <th>説明</th><td>{{ form.description }}</td>
      </tr>
      <tr>
        <th>価格</th><td>{{ form.price }}</td>
      </tr>
      <tr>
        <th>オススメ</th><td>{{ form.is_recommended }}</td>
      </tr>
    </table>

    <button type="button" class="back-btn" data-action="{% url 'samazon_admin:product_list' %}">戻る</button>
    <button>登録</button>
  </form>
{% endblock %}

samazon_admin/templates/samazon_admin/product/detail.html
{% extends 'samazon_admin/base.html' %}

{% block content %}
  <form method="post" action="{% url 'samazon_admin:product_delete' product.pk %}">
    {% csrf_token %}
    <!-- base.htmlのjqueryに削除確認処理がある -->
    <button type="button" class="delete-btn">削除</button>
  </form>

  <form action="{% url 'samazon_admin:product_update' product.pk %}">
    <table>
      <tbody>
        <tr>
          <td colspan="2"><img src="{{ product.photo.url }}" alt="{{ product.name }}" width="300"></td>
        </tr>
        <tr>
          <th>カテゴリー</th><td>{{ product.category.name }}</td>
        </tr>
        <tr>
          <th>商品名</th><td>{{ product.name }}</td>
        </tr>
        <tr>
          <th>説明</th><td>{{ product.description }}</td>
        </tr>
        <tr>
          <th>価格</th><td>{{ product.price }}</td>
        </tr>
        <tr>
          <th>オススメ</th><td>{% if product.is_recommended %} yes {% else %} no {% endif %}</td>
        </tr>
      </tbody>
    </table>

    <!-- base.htmlのjqueryに戻る処理がある -->
    <button type="button" class="back-btn" data-action="{% url 'samazon_admin:product_list' %}">戻る</button>
    <button>編集</button>
  </form>
{% endblock %}

samazon_admin/templates/samazon_admin/product/list.html
{% extends 'samazon_admin/base.html' %}

{% block javascript %}
  <script>
    $(function () {
      // 並び替えセレクトボックスのオプションの値を１つ１つチェックする
      $('select[name=order_by] option').each(function () {
        // オプションの値が、直前に選択されたオプションの値であるか調べる
        if ($(this).val() === '{{ request.GET.order_by }}') {
          // オプションの値が、直前に選択されたオプションの値である場合、selected属性を追加する
          $(this).attr('selected', true);
        }
      });

      // 並び替えセレクトボックスの値が変更された際の処理
      $('select[name=order_by]').change(function () {
        // id="search-form"のformタグを取得
        const $form = $('#search-form');
        // formタグのaction属性のURLにリクエストする
        $form.submit();
      });

      // ページのリンクをクリックした際の処理
      $('.page').click(function () {
        // ページ番号を表すinputタグのvalue属性の値を、クリックされたページの値にする
        $('input[name=page]').val($(this).data('page'));
        // id="order-form"のformタグを取得
        const $form = $('#search-form');
        // formタグのaction属性のURLにリクエストする
        $form.submit();
        // aタグのリンクの効果を無効にする
        return false;
      });
    });
  </script>
{% endblock %}

{% block content %}
  <form id="search-form">
    <input type="hidden" name="page" value="1">

    <table>
      <tr>
        <td>
          <select name="order_by">
            <option value="pk">並び替え</option>
            <option value="price">価格の安い順</option>
            <option value="-price">価格の高い順</option>
            <option value="created_at">出品の古い順</option>
            <option value="-created_at">出品の新しい順</option>
          </select>
        </td>
        <td></td>
      </tr>
      <tr>
        <td>商品名</td>
        <td><input name="keyword" value="{{ request.GET.keyword }}"></td>
      </tr>
    </table>

    <button>検索</button>
  </form>

  <hr>
  <br>

  <form action="{% url 'samazon_admin:product_create' %}">
    <button>新規登録</button>
  </form>

  <table>
    <thead>
      <tr>
        <th>ID</th>
        <th>画像</th>
        <th>カテゴリー</th>
        <th>商品名</th>
        <th>価格</th>
      </tr>
    </thead>
    <tbody>
      {% for product in object_list %}
        <tr>
          <td><a href="{% url 'samazon_admin:product_detail' product.pk %}">{{ product.pk }}</a></td>
          <td><img src="{{ product.photo.url }}" alt="{{ product.name }}" width="100"></td>
          <td>{{ product.category.name }}</td>
          <td>{{ product.name }}</td>
          <td>{{ product.price }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>

  {% if paginator.num_pages != 1 %}
    {% if page_obj.has_previous %}
      <a class="page" href="" data-page="{{ page_obj.number|add:-1 }}">prev | </a>
    {% else %}
      <span>prev | </span>
    {% endif %}

    {% for page in paginator.page_range %}
      {% if page == page_obj.number %}
        <span>{{ page }} | </span>
      {% else %}
        <a class="page" href="" data-page="{{ page }}">{{ page }} | </a>
      {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}
      <a class="page" href="" data-page="{{ page_obj.number|add:1 }}">next</a>
    {% else %}
      <span>next</span>
    {% endif %}
  {% endif %}
{% endblock %}

samazon_admin/templates/samazon_admin/product/update.html
{% extends 'samazon_admin/base.html' %}

{% block content %}
  <!-- 画像を送信するために、enctype="multipart/form-data"を使用 -->
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}

    <table>
      <tr>
        <th>画像</th><td>{{ form.photo }}</td>
      </tr>
      <tr>
        <th>カテゴリー</th><td>{{ form.category }}</td>
      </tr>
      <tr>
        <th>商品名</th><td>{{ form.name }}</td>
      </tr>
      <tr>
        <th>説明</th><td>{{ form.description }}</td>
      </tr>
      <tr>
        <th>価格</th><td>{{ form.price }}</td>
      </tr>
      <tr>
        <th>オススメ</th><td>{{ form.is_recommended }}</td>
      </tr>
    </table>

    <button type="button" class="back-btn" data-action="{% url 'samazon_admin:product_detail' form.instance.pk %}">戻る</button>
    <button>編集</button>
  </form>
{% endblock %}