core/urls.py
from django.urls import path

from core import views

app_name = 'core'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('categories/<int:pk>/products/', views.ProductListView.as_view(), name='product_list'),
    path('products/<int:pk>/', views.ProductDetailView.as_view(), name='product_detail'),
    path('products/<int:pk>/review/', views.ProductReviewView.as_view(), name='product_review'),
    path('cart/', views.CartView.as_view(), name='cart'),
    path('cart/add/', views.CartAddView.as_view(), name='cart_add'),
    path('cart/<int:pk>/update/', views.CartUpdateView.as_view(), name='cart_update'),
    path('cart/delete/', views.CartDeleteView.as_view(), name='cart_delete'),
    path('favorite/', views.FavoriteView.as_view(), name='favorite'),
    path('favorite/add/', views.FavoriteAddDeleteView.as_view(), name='favorite_add_delete'),
    path('favorite/delete/', views.FavoriteDeleteView.as_view(), name='favorite_delete'),
    path('mypage/', views.MyPageView.as_view(), name='mypage'),
    path('mypage/profile/update/', views.ProfileUpdateView.as_view(), name='profile_update'),
    path('mypage/credit_card/create', views.CreditCardCreateView.as_view(), name='credit_card_create'),
    path('mypage/address/update/', views.AddressUpdateView.as_view(), name='address_update'),
    path('mypage/user/delete/', views.UserDeleteView.as_view(), name='user_delete'),
    path('search/', views.SearchView.as_view(), name='search'),
    path('payment/', views.PaymentView.as_view(), name='payment')
]

samazon/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('samazon_admin/', include('samazon_admin.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models

from django.contrib.auth.hashers import check_password, make_password


class DatedModel(models.Model):
    created_at = models.DateTimeField(db_index=True, auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        # DatedModelは単体で使用するのではなく、他のモデルに継承されて使用されることを表す。
        abstract = True


class User(DatedModel):
    username = models.CharField(max_length=100)
    email = models.EmailField(unique=True, error_messages={'unique': '使用済みメールアドレスです'})
    postal_code = models.CharField(max_length=100)
    address = models.CharField(max_length=100)
    phone = models.CharField(max_length=100)
    password = models.CharField(max_length=100)
    deleted_at = models.DateTimeField(blank=True, null=True)
    stripe_customer_id = models.CharField(max_length=100, blank=True, null=True)
    backend = models.CharField(max_length=100, blank=True, null=True)
    last_login = models.DateTimeField(blank=True, null=True)

    @property
    def is_authenticated(self):
        """
        Always return True. This is a way to tell if the user has been
        authenticated in templates.
        """
        return True

    def set_password(self, raw_password):
        self.password = make_password(raw_password)
        self._password = raw_password

    def check_password(self, raw_password):
        """
        Return a boolean of whether the raw_password was correct. Handles
        hashing formats behind the scenes.
        """

        def setter(raw_password):
            self.set_password(raw_password)
            # Password hash upgrades shouldn't be considered password changes.
            self._password = None
            self.save(update_fields=["password"])

        return check_password(raw_password, self.password, setter)

    def cart_total_amount(self):
        return sum(cart.sum() for cart in self.carts.all())


class MajorCategory(DatedModel):
    name = models.CharField(max_length=100)
    description = models.TextField()

    def __str__(self):
        return self.name


class Category(DatedModel):
    major_category = models.ForeignKey(MajorCategory, on_delete=models.CASCADE, related_name='categories')
    name = models.CharField(max_length=100)
    description = models.TextField()

    def __str__(self):
        # 商品登録画面のカテゴリー一覧に表示される、カテゴリーの表示名を表す
        return self.name


class Product(DatedModel):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='products')
    name = models.CharField(max_length=100)
    description = models.TextField()
    price = models.IntegerField()
    photo = models.ImageField()
    is_recommended = models.BooleanField(default=False)


class Cart(DatedModel):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='carts')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='carts')
    qty = models.IntegerField()

    def sum(self):
        return self.product.price * self.qty


class Favorite(DatedModel):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='favorites')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='favorites')


class Review(DatedModel):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='reviews')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='reviews')
    score = models.IntegerField()
    body = models.TextField()

    @property
    def score_star(self):
        return '★' * self.score


class Order(DatedModel):
    payment_intent_id = models.CharField(max_length=100)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='orders')
    total_amount = models.IntegerField()


class PurchaseHistory(DatedModel):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='purchase_histories')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='purchase_histories')
    qty = models.IntegerField()
    amount = models.IntegerField()

core/views/cart.py
from django.http import JsonResponse
from django.shortcuts import redirect, render
from django.views.generic import View

from core.models import Cart


class CartView(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'core/cart.html')


class CartAddView(View):
    def post(self, request, *args, **kwargs):
        cart, added = Cart.objects.get_or_create(
            defaults={'qty': request.POST['qty']},
            user=request.user,
            product_id=request.POST['product_id']
        )
        if not added:
            cart.qty += int(request.POST['qty'])
            cart.save()
        return redirect('core:product_detail', request.POST['product_id'])


class CartUpdateView(View):
    def post(self, request, *args, **kwargs):
        Cart.objects.filter(pk=kwargs['pk']).update(qty=request.POST['qty'])
        return redirect('core:cart')


class CartDeleteView(View):
    def post(self, request, *args, **kwargs):
        Cart.objects.filter(pk__in=request.POST.getlist('cart_ids[]')).delete()
        return JsonResponse({})

core/views/favorite.py
from django.http import JsonResponse
from django.shortcuts import redirect, render
from django.views.generic import View

from core.models import Favorite


class FavoriteView(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'core/favorite.html')


class FavoriteAddDeleteView(View):
    def post(self, request, *args, **kwargs):
        favorite, added = Favorite.objects.get_or_create(
            user=request.user,
            product_id=request.POST['product_id']
        )
        if not added:
            favorite.delete()
        return redirect('core:product_detail', request.POST['product_id'])


class FavoriteDeleteView(View):
    def post(self, request, *args, **kwargs):
        Favorite.objects.filter(pk__in=request.POST.getlist('favorite_ids[]')).delete()
        return JsonResponse({})

core/views/home.py
from django.shortcuts import render
from django.views.generic import View

from core.models import Product
from core.views.mixins import CategoryMixin


class HomeView(CategoryMixin, View):
    def get(self, request, *args, **kwargs):
        context = {
            'categories': self.get_categories(),  # 継承しているCategoryMixinのget_categoriesメソッドを実行
            'recommends': Product.objects.filter(is_recommended=True)[:3],  # 先頭から３つのデータを取得
            'new_arrivals': Product.objects.all().order_by('-pk')[:4],  # 末尾から４つのデータを取得
        }
        return render(request, 'core/home.html', context)

core/views/mixins.py
from django.contrib.auth.mixins import LoginRequiredMixin as BaseLoginRequiredMixin
from django.core.paginator import Paginator
from django.urls import reverse_lazy

from core.models import Category


class LoginRequiredMixin(BaseLoginRequiredMixin):
    login_url = reverse_lazy('core:login')


class CategoryMixin:
    def get_categories(self):
        categories = {}
        for category in Category.objects.all():
            # categories辞書のキーにmajor_category_nameが存在しない場合、デフォルト値として空のリストを追加しておく
            categories.setdefault(category.major_category.name, [])
            # 同じmajor_category_nameのcategoryをリストに追加していく
            categories[category.major_category.name].append(category)
        return categories.items()


class PaginationMixin:
    paginate_by = 3

    def get_page_data(self, queryset):
        paginator = Paginator(queryset, self.paginate_by)
        # URLにpageパラメータがない場合は、デフォルト値として1を使用する
        page_number = self.request.GET.get('page', 1)
        page = paginator.page(page_number)
        return {
            'paginator': paginator,
            'page_obj': page,
            'object_list': page.object_list
        }

core/views/mypage.py
import stripe
from datetime import datetime

from django.conf import settings
from django.http import JsonResponse
from django.shortcuts import redirect, render
from django.views.generic import View

from core.forms.mypage import AddressUpdateForm
from core.models import User
from core.views.mixins import LoginRequiredMixin


class MyPageView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        return render(request, 'core/mypage.html')


class ProfileUpdateView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        return render(request, 'core/profile_update.html')

    def post(self, request, *args, **kwargs):
        for field_name, value in request.POST.items():
            # Userモデルにfield_nameというフィールドがあるかチェックする
            if hasattr(request.user, field_name):
                # フィールドがある場合、その値をvalueで上書きする
                setattr(request.user, field_name, value)
        # 上書きしたデータを保存する
        request.user.save()
        return redirect('core:profile_update')


class CreditCardCreateView(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'core/credit_card.html')

    def post(self, request, *args, **kwargs):
        stripe.api_key = settings.STRIPE_API_KEY

        try:
            payment_method = stripe.PaymentMethod.create(
                type='card',
                card={
                    'number': request.POST['number'],
                    'exp_month': request.POST['exp_month'],
                    'exp_year': request.POST['exp_year'],
                    'cvc': request.POST['cvc'],
                },
            )

            customer = stripe.Customer.create(
                email=request.user.email,
                payment_method=payment_method
            )
        except stripe.error.CardError as e:
            return JsonResponse({
                'status': 'failed',
                'stripeCode': e.code,
                'message': e.user_message
            })

        User.objects.filter(pk=request.user.pk).update(stripe_customer_id=customer.id)

        return JsonResponse({'status': 'success'})


class AddressUpdateView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        form = AddressUpdateForm(instance=request.user)
        return render(request, 'core/address_update.html', {'form': form})

    def post(self, request, *args, **kwargs):
        form = AddressUpdateForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('core:mypage')
        return render(request, 'core/address_update.html', {'form': form})


class UserDeleteView(View):
    def post(self, request, *args, **kwargs):
        User.objects.filter(pk=request.user.pk).update(deleted_at=datetime.now())
        return redirect('core:login')

core/views/payment.py
import stripe

from django.conf import settings
from django.http import JsonResponse
from django.views.generic import View

from core.models import Order, PurchaseHistory


class PaymentView(View):
    def post(self, request, *args, **kwargs):
        stripe.api_key = settings.STRIPE_API_KEY

        try:
            payment_intent = stripe.PaymentIntent.create(
                customer=request.user.stripe_customer_id,
                amount=request.POST['amount'],
                currency='jpy',
                payment_method_types=['card'],
            )

            payment_methods = stripe.PaymentMethod.list(
                customer=request.user.stripe_customer_id,
                type='card',
            )

            payment_method = payment_methods['data'][0]['id']

            response = stripe.PaymentIntent.confirm(
                payment_intent.id,
                payment_method=payment_method,
            )
        except stripe.error.CardError as e:
            return JsonResponse({
                'status': 'failed',
                'stripeCode': e.code,
                'message': e.user_message
            })

        order = Order.objects.create(
            payment_intent_id=response.id,
            user=request.user,
            total_amount=request.POST['amount'],
        )

        for cart in request.user.carts.all():
            PurchaseHistory.objects.create(
                order=order,
                product=cart.product,
                qty=cart.qty,
                amount=cart.sum(),
            )

        request.user.carts.all().delete()

        return JsonResponse({'status': 'succeeded'})

core/views/product.py
from django.shortcuts import redirect, render
from django.views.generic import View

from core.models import Category, Product
from core.views.mixins import CategoryMixin, PaginationMixin


class ProductListView(CategoryMixin, PaginationMixin, View):
    def get(self, request, *args, **kwargs):
        category = Category.objects.get(pk=kwargs['pk'])
        # URLにorder_byパラメータがない場合は、idの昇順で並び替える
        products = category.products.all().order_by(request.GET.get('order_by', 'id'))
        context = {
            'category': category,
            'categories': self.get_categories(),  # 継承しているCategoryMixinのget_categoriesメソッドを実行
            **self.get_page_data(products)  # 継承しているPaginationMixinのget_page_dataメソッドを実行
        }
        return render(request, 'core/product/list.html', context)


class ProductDetailView(CategoryMixin, PaginationMixin, View):
    paginate_by = 2

    def get(self, request, *args, **kwargs):
        product = Product.objects.get(pk=kwargs['pk'])
        favorite_added = request.user.is_authenticated and request.user.favorites.filter(product=product).exists()
        context = {
            'product': product,
            'categories': self.get_categories(),  # 継承しているCategoryMixinのget_categoriesメソッドを実行
            'favorite_added': favorite_added,
            **self.get_page_data(product.reviews.all()),  # 継承しているPaginationMixinのget_page_dataメソッドを実行
        }
        return render(request, 'core/product/detail.html', context)


class ProductReviewView(View):
    def post(self, request, *args, **kwargs):
        product = Product.objects.get(pk=kwargs['pk'])
        product.reviews.create(
            user=request.user,
            score=request.POST['score'],
            body=request.POST['body']
        )
        return redirect('core:product_detail', product.pk)

core/views/search.py
from django.db.models import Avg, Q
from django.shortcuts import render
from django.views.generic import View

from core.models import Product
from core.views.mixins import CategoryMixin, PaginationMixin


class SearchView(CategoryMixin, PaginationMixin, View):
    def get(self, request, *args, **kwargs):
        # 検索用パラメータを表すQオブジェクト
        q = Q()
        for param_name, value in request.GET.items():
            if not value:
                continue
            if param_name == 'search_word':
                # プロダクト名に検索ワードが部分一致するか
                q &= Q(name__contains=value)
            elif param_name == 'category_name':
                # プロダクトのカテゴリーに一致するか
                q &= Q(category__name=value)
            elif param_name == 'star':
                # プロダクトのレビューの星がリクエスト値以上か
                q &= Q(star__gte=value)

        # valuesメソッドにより、プロダクトのpkでレコードをグループ化する。
        # annotateメソッドにより、レビューのスコアの平均値を求める。
        # Qオブジェクトにより、レコードをフィルターする。
        products = Product.objects.values('pk').annotate(star=Avg('reviews__score')).filter(q)

        # フィルター後にproductsに代入されているのはQuerySetではないので、フィルター後に残ったプロダクトのidにより、QuerySetを取得する
        products = Product.objects.filter(pk__in=[p['pk'] for p in products])

        context = {
            'categories': self.get_categories(),
            **self.get_page_data(products)
        }
        return render(request, 'core/search.html', context)

core/templates/core/address_update.html
{% extends 'core/base.html' %}

{% block content %}
  <h4>お届け先変更</h4>

  <form method="post">
    {% csrf_token %}

    <table>
      <tr>
        <td><label for="id_username">氏名</label></td>
        <td>{{ form.username }}</td>
      </tr>
      <tr>
        <td><label for="id_email">メールアドレス</label></td>
        <td>
          {{ form.email }}<br>
          {% for error in form.email.errors %}
            {{ error }}
          {% endfor %}
        </td>
      </tr>
      <tr>
        <td><label for="id_postal_code">郵便番号</label></td>
        <td>{{ form.postal_code }}</td>
      </tr>
      <tr>
        <td><label for="id_address">住所</label></td>
        <td>{{ form.address }}</td>
      </tr>
      <tr>
        <td><label for="id_phone">電話番号</label></td>
        <td>{{ form.phone }}</td>
      </tr>
    </table>

    <button>保存する</button>
  </form>
{% endblock %}

core/templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Title</title>
  <script src="{% static 'core/js/jquery-3.5.1.min.js' %}"></script>
  <link rel="stylesheet" href="{% static 'core/css/bootstrap.min.css' %}">
  {% block javascript %}{% endblock %}
  {% block css %}{% endblock %}
  <script>
    $(function () {
      $('.search-btn').click(function () {
        // search.htmlを開いている場合はid="search-param-form"がhtml上にあるが、そのほかのテンプレートの場合は存在しない
        const $searchParamForm = $('#search-param-form');
        // id="search-param-form"があるかチェックする
        if ($searchParamForm.length !== 0) {
          // search.htmlを開いている場合は、id="search-param-form"があるので、こちらの処理が実行される
          // 検索欄の値を取得する
          const searchWord = $('input[name=search_word]').val();
          // 検索欄の値を、search.html上に定義されている、<input type="hidden" name="search_word">のvalueに代入する
          $('input[type="hidden"][name=search_word]').val(searchWord);
          // search.html上にあるid="search-param-form"のformを送信する
          $searchParamForm.submit();
        } else {
          // search.htmlを開いていない場合は、id="search-param-form"がないので、こちらの処理が実行される
          // このbase.html上のformを使用する
          const $searchForm = $(this).parents('form');
          // formを送信する
          $searchForm.submit();
        }
      });
    });
  </script>

  <style>
    .samazon a {
        text-decoration: none;
        color: black;
    }
  </style>
</head>
<body>
  <div class="container-fluid">
    <h1 class="samazon"><a href="{% url 'core:home' %}">Samazon</a></h1>
    <ul>
      {% if not user.is_authenticated %}
        <li><a href="{% url 'core:register' %}">新規登録</a></li>
        <li><a href="{% url 'core:login' %}">ログイン</a></li>
      {% else %}
        <li><a href="{% url 'core:cart' %}">カート</a></li>
        <li><a href="{% url 'core:favorite' %}">お気に入り</a></li>
        <li><a href="{% url 'core:mypage' %}">マイページ</a></li>
      {% endif %}
    </ul>
    <form action="{% url 'core:search' %}">
      <!-- URLにsearch_wordパラメータがある場合、その値を初期値とする -->
      <input name="search_word" value="{{ request.GET.search_word }}">
      <button type="button" class="search-btn">検索</button>
    </form>

    <hr>

    <form id="form"></form>

    {% block content %}{% endblock %}
  </div>
</body>
</html>

core/templates/core/cart.html
{% extends 'core/base.html' %}

{% block javascript %}
  <script>
    $(function () {
      function deleteCart(cartIds) {
        $.ajax({
          headers: { 'X-CSRFToken': '{{ csrf_token }}' },
          url: '/cart/delete/',
          method: 'post',
          data: { cart_ids: cartIds }
        }).done(function (response) {
          location.reload();
        })
      }

      $('.all-delete-btn').click(function () {
        if (confirm('商品をすべて削除してもよろしいですか？')) {
          const cartIds = $('.delete-btn').map(function () {
            return $(this).data('cart_id');
          }).get();
          deleteCart(cartIds);
        }
      });

      $('.delete-btn').click(function () {
        const cartId = [$(this).data('cart_id')];
        deleteCart(cartId);
      });

      $('.payment-btn').click(function () {
        if (!('{{ user.stripe_customer_id }}')) {
          alert('クレジットカードを登録してください');
          return false;
        }

        if (confirm('購入を確定してもよろしいですか？')) {
          $.ajax({
            headers: { 'X-CSRFToken': '{{ csrf_token }}' },
            url: '/payment/',
            method: 'post',
            data: { amount: '{{ user.cart_total_amount }}' },
          }).done(function (response) {
            if (response['status'] === 'failed') {
              $('.error').text('');
              $('.succeeded').text('');
              let found = false;
              $('.error').each(function () {
                if ($(this).attr('id') === response['stripeCode']) {
                  $(this).text(response['message']);
                  found = true;
                }
              });
              if (!found) {
                $('#other-error').text('入力情報に誤りがあります');
              }
              console.log(response['status'])
              console.log(response['message'])
            } else {
              $('.error').text('');
              $('.succeeded').text('');
              console.log('success');
              $(`#customer_id_succeeded`).text(response['status']);
            }
          });
        }
      });
    });
  </script>
{% endblock %}

{% block css %}
  <style>
    #qty {
      width: 3em;
    }
  </style>
{% endblock %}

{% block content %}
  {% if user.carts.count > 0 %}
    <table>
      <thead>
        <tr>
          <th></th>
          <th>数量</th>
          <th>合計</th>
          <th><button class="all-delete-btn">すべて削除</button></th>
        </tr>
      </thead>
      <tbody>
        {% for cart in user.carts.all %}
          <tr>
            <td>
              <a href="{% url 'core:product_detail' cart.product.pk %}">
                <img src="{{ cart.product.photo.url }}" width="200">
              </a>
              {{ cart.product.name }}
            </td>
            <td>
              <form method="post" action="{% url 'core:cart_update' cart.pk %}">
                {% csrf_token %}
                <input type="number" id="qty" name="qty" value="{{ cart.qty }}">
                <button>変更</button>
              </form>
            </td>
            <td>¥{{ cart.sum }}</td>
            <td><button class="delete-btn" data-cart_id="{{ cart.pk }}">削除</button></td>
          </tr>
        {% endfor %}
      </tbody>
    </table>

    <button class="payment-btn">購入を確定する</button>
    <span class="succeeded" id="customer_id_succeeded"></span>
  {% else %}
    現在カートに商品はありません
  {% endif %}
{% endblock %}

core/templates/core/category.html
{% for major_category_name, categories in categories %}
  <h3>{{ major_category_name }}</h3>
  <ul>
    {% for category in categories %}
      <li><a href="{% url 'core:product_list' category.pk %}">{{ category.name }}</a></li>
    {% endfor %}
  </ul>
{% endfor %}

core/templates/core/favorite.html
{% extends 'core/base.html' %}

{% block javascript %}
  <script>
    $(function () {
      function deleteFavorite(favoriteIds) {
        $.ajax({
          headers: { 'X-CSRFToken': '{{ csrf_token }}' },
          url: '/favorite/delete/',
          method: 'post',
          data: { favorite_ids: favoriteIds }
        }).done(function (response) {
          location.reload();
        })
      }

      $('.all-delete-btn').click(function () {
        if (confirm('商品をすべて削除してもよろしいですか？')) {
          const favoriteIds = $('.delete-btn').map(function () {
            return $(this).data('favorite_id');
          }).get();
          deleteFavorite(favoriteIds);
        }
      });

      $('.delete-btn').click(function () {
        const favoriteId = [$(this).data('favorite_id')];
        deleteFavorite(favoriteId);
      });
    });
  </script>
{% endblock %}

{% block content %}
  {% if user.favorites.count > 0 %}
    <table>
      <thead>
        <tr>
          <th></th>
          <th><button class="all-delete-btn">すべて削除</button></th>
        </tr>
      </thead>
      <tbody>
        {% for favorite in user.favorites.all %}
          <tr>
            <td>
              <a href="{% url 'core:product_detail' favorite.product.pk %}">
                <img src="{{ favorite.product.photo.url }}" width="200">
              </a>
              {{ favorite.product.name }}
            </td>
            <td><button class="delete-btn" data-favorite_id="{{ favorite.pk }}">削除</button></td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  {% else %}
    現在お気に入り商品はありません
  {% endif %}
{% endblock %}

core/templates/core/mypage.html
{% extends 'core/base.html' %}

{% block content %}
  <ul>
    <li><a href="{% url 'core:profile_update' %}">会員情報編集</a></li>
    <li><a href="{% url 'core:credit_card_create' %}">クレジットカード登録</a></li>
    <li><a href="{% url 'core:address_update' %}">お届け先の変更</a></li>
    <li><a href="{% url 'core:logout' %}">ログアウト</a></li>
  </ul>
{% endblock %}

core/templates/core/profile_update.html
{% extends 'core/base.html' %}

{% block javascript %}
  <script>
    $(function () {
      // 編集ボタンがクリックされた際の処理
      $('.edit-btn').click(function () {
        // 編集ボタンの親タグであるclass="show"属性のdivタグを非表示にする
        $(this).parents('.show').hide();
        // 編集ボタンの親タグであるtdの子要素に定義されている、class="edit"属性のdivタグを表示させる
        $(this).parents('td').children('.edit').show();
      });

      // キャンセルボタンがクリックされた際の処理
      $('.cancel-btn').click(function () {
        // キャンセルボタンの親タグであるclass="edit"属性のdivタグを非表示にする
        $(this).parents('.edit').hide();
        // キャンセルボタンの親タグであるtdの子要素に定義されている、class="show"属性のdivタグを表示させる
        $(this).parents('td').children('.show').show();
      })

      $('.delete-btn').click(function () {
        if (confirm('退会してもよろしいですか？')) {
          const $form = $(this).parents('form');
          $form.submit();
        }
      });
    });
  </script>
{% endblock %}

{% block content %}
  <table>
    <tr>
      <th>
        <label>氏名</label>
      </th>
      <td>
        <div class="show">
          <label for="username">{{ user.username }}</label>
          <button class="edit-btn">編集</button>
        </div>
        <div class="edit" style="display: none">
          <form method="post" action="{% url 'core:profile_update' %}">
            {% csrf_token %}
            <input id="username" name="username" value="{{ user.username }}">
            <button class="save-btn">保存</button>
            <button type="button" class="cancel-btn">キャンセル</button>
          </form>
        </div>
      </td>
    </tr>
    <tr>
      <th>
        <label>メールアドレス</label>
      </th>
      <td>
        <div class="show">
          <label for="email">{{ user.email }}</label>
          <button class="edit-btn">編集</button>
        </div>
        <div class="edit" style="display: none">
          <form method="post" action="{% url 'core:profile_update' %}">
            {% csrf_token %}
            <input id="email" type="email" name="email" value="{{ user.email }}">
            <button class="save-btn">保存</button>
            <button type="button" class="cancel-btn">キャンセル</button>
          </form>
        </div>
      </td>
    </tr>
    <tr>
      <th>
        <label>電話番号</label>
      </th>
      <td>
        <div class="show">
          <label for="phone">{{ user.phone }}</label>
          <button class="edit-btn">編集</button>
        </div>
        <div class="edit" style="display: none">
          <form method="post" action="{% url 'core:profile_update' %}">
            {% csrf_token %}
            <input id="phone" name="phone" value="{{ user.phone }}">
            <button class="save-btn">保存</button>
            <button type="button" class="cancel-btn">キャンセル</button>
          </form>
        </div>
      </td>
    </tr>
  </table>

  <form method="post" action="{% url 'core:user_delete' %}">
    {% csrf_token %}
    <button type="button" class="delete-btn">退会する</button>
  </form>
{% endblock %}