core/urls.py
from django.urls import path

from core import views

app_name = 'core'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('categories/<int:pk>/products/', views.ProductListView.as_view(), name='product_list'),
    path('products/<int:pk>/', views.ProductDetailView.as_view(), name='product_detail'),
    path('products/<int:pk>/review/', views.ProductReviewView.as_view(), name='product_review'),
    path('cart/', views.CartView.as_view(), name='cart'),
    path('cart/add/', views.CartAddView.as_view(), name='cart_add'),
    path('cart/<int:pk>/update/', views.CartUpdateView.as_view(), name='cart_update'),
    path('cart/delete/', views.CartDeleteView.as_view(), name='cart_delete'),
    path('favorite/', views.FavoriteView.as_view(), name='favorite'),
    path('favorite/add/', views.FavoriteAddDeleteView.as_view(), name='favorite_add_delete'),
    path('favorite/delete/', views.FavoriteDeleteView.as_view(), name='favorite_delete'),
    path('mypage/', views.MyPageView.as_view(), name='mypage'),
    path('mypage/profile/update/', views.ProfileUpdateView.as_view(), name='profile_update'),
    path('mypage/credit_card/create', views.CreditCardCreateView.as_view(), name='credit_card_create'),
    path('mypage/address/update/', views.AddressUpdateView.as_view(), name='address_update'),
    path('mypage/user/delete/', views.UserDeleteView.as_view(), name='user_delete'),
    path('search/', views.SearchView.as_view(), name='search'),
    path('payment/', views.PaymentView.as_view(), name='payment')
]

samazon/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('samazon_admin/', include('samazon_admin.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/forms/mypage.py
from django import forms

from core.models import User


class AddressUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'postal_code', 'address', 'phone']
        widgets = {
            'username': forms.TextInput(attrs={'placeholder': '侍太郎'}),
            'email': forms.EmailInput(attrs={'placeholder': 'samurai@samurai.com'}),
            'postal_code': forms.TextInput(attrs={'placeholder': '150-0043'}),
            'address': forms.TextInput(attrs={'placeholder': '東京都渋谷区道玄坂２丁目１１−１'}),
            'phone': forms.TextInput(attrs={'placeholder': '03-5790-9039'}),
        }

core/views/cart.py
from django.http import JsonResponse
from django.shortcuts import redirect, render
from django.views.generic import View

from core.models import Cart


class CartView(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'core/cart.html')


class CartAddView(View):
    def post(self, request, *args, **kwargs):
        cart, added = Cart.objects.get_or_create(
            defaults={'qty': request.POST['qty']},
            user=request.user,
            product_id=request.POST['product_id']
        )
        if not added:
            cart.qty += int(request.POST['qty'])
            cart.save()
        return redirect('core:product_detail', request.POST['product_id'])


class CartUpdateView(View):
    def post(self, request, *args, **kwargs):
        Cart.objects.filter(pk=kwargs['pk']).update(qty=request.POST['qty'])
        return redirect('core:cart')


class CartDeleteView(View):
    def post(self, request, *args, **kwargs):
        Cart.objects.filter(pk__in=request.POST.getlist('cart_ids[]')).delete()
        return JsonResponse({})

core/views/favorite.py
from django.http import JsonResponse
from django.shortcuts import redirect, render
from django.views.generic import View

from core.models import Favorite


class FavoriteView(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'core/favorite.html')


class FavoriteAddDeleteView(View):
    def post(self, request, *args, **kwargs):
        favorite, added = Favorite.objects.get_or_create(
            user=request.user,
            product_id=request.POST['product_id']
        )
        if not added:
            favorite.delete()
        return redirect('core:product_detail', request.POST['product_id'])


class FavoriteDeleteView(View):
    def post(self, request, *args, **kwargs):
        Favorite.objects.filter(pk__in=request.POST.getlist('favorite_ids[]')).delete()
        return JsonResponse({})

core/views/home.py
from django.shortcuts import render
from django.views.generic import View

from core.models import Product
from core.views.mixins import CategoryMixin


class HomeView(CategoryMixin, View):
    def get(self, request, *args, **kwargs):
        context = {
            'categories': self.get_categories(),  # 継承しているCategoryMixinのget_categoriesメソッドを実行
            'recommends': Product.objects.filter(is_recommended=True)[:3],  # 先頭から３つのデータを取得
            'new_arrivals': Product.objects.all().order_by('-pk')[:4],  # 末尾から４つのデータを取得
        }
        return render(request, 'core/home.html', context)

core/views/mixins.py
from django.contrib.auth.mixins import LoginRequiredMixin as BaseLoginRequiredMixin
from django.core.paginator import Paginator
from django.urls import reverse_lazy

from core.models import Category


class LoginRequiredMixin(BaseLoginRequiredMixin):
    login_url = reverse_lazy('core:login')


class CategoryMixin:
    def get_categories(self):
        categories = {}
        for category in Category.objects.all():
            # categories辞書のキーにmajor_category_nameが存在しない場合、デフォルト値として空のリストを追加しておく
            categories.setdefault(category.major_category.name, [])
            # 同じmajor_category_nameのcategoryをリストに追加していく
            categories[category.major_category.name].append(category)
        return categories.items()


class PaginationMixin:
    paginate_by = 3

    def get_page_data(self, queryset):
        paginator = Paginator(queryset, self.paginate_by)
        # URLにpageパラメータがない場合は、デフォルト値として1を使用する
        page_number = self.request.GET.get('page', 1)
        page = paginator.page(page_number)
        return {
            'paginator': paginator,
            'page_obj': page,
            'object_list': page.object_list
        }

core/views/mypage.py
import stripe
from datetime import datetime

from django.conf import settings
from django.http import JsonResponse
from django.shortcuts import redirect, render
from django.views.generic import View

from core.forms.mypage import AddressUpdateForm
from core.models import User
from core.views.mixins import LoginRequiredMixin


class MyPageView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        return render(request, 'core/mypage.html')


class ProfileUpdateView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        return render(request, 'core/profile_update.html')

    def post(self, request, *args, **kwargs):
        for field_name, value in request.POST.items():
            # Userモデルにfield_nameというフィールドがあるかチェックする
            if hasattr(request.user, field_name):
                # フィールドがある場合、その値をvalueで上書きする
                setattr(request.user, field_name, value)
        # 上書きしたデータを保存する
        request.user.save()
        return redirect('core:profile_update')


class CreditCardCreateView(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'core/credit_card.html')

    def post(self, request, *args, **kwargs):
        stripe.api_key = settings.STRIPE_API_KEY

        try:
            payment_method = stripe.PaymentMethod.create(
                type='card',
                card={
                    'number': request.POST['number'],
                    'exp_month': request.POST['exp_month'],
                    'exp_year': request.POST['exp_year'],
                    'cvc': request.POST['cvc'],
                },
            )

            customer = stripe.Customer.create(
                email=request.user.email,
                payment_method=payment_method
            )
        except stripe.error.CardError as e:
            return JsonResponse({
                'status': 'failed',
                'stripeCode': e.code,
                'message': e.user_message
            })

        User.objects.filter(pk=request.user.pk).update(stripe_customer_id=customer.id)

        return JsonResponse({'status': 'success'})


class AddressUpdateView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        form = AddressUpdateForm(instance=request.user)
        return render(request, 'core/address_update.html', {'form': form})

    def post(self, request, *args, **kwargs):
        form = AddressUpdateForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('core:mypage')
        return render(request, 'core/address_update.html', {'form': form})


class UserDeleteView(View):
    def post(self, request, *args, **kwargs):
        User.objects.filter(pk=request.user.pk).update(deleted_at=datetime.now())
        return redirect('core:login')

core/views/payment.py
import stripe

from django.conf import settings
from django.http import JsonResponse
from django.views.generic import View

from core.models import Order, PurchaseHistory


class PaymentView(View):
    def post(self, request, *args, **kwargs):
        stripe.api_key = settings.STRIPE_API_KEY

        try:
            payment_intent = stripe.PaymentIntent.create(
                customer=request.user.stripe_customer_id,
                amount=request.POST['amount'],
                currency='jpy',
                payment_method_types=['card'],
            )

            payment_methods = stripe.PaymentMethod.list(
                customer=request.user.stripe_customer_id,
                type='card',
            )

            payment_method = payment_methods['data'][0]['id']

            response = stripe.PaymentIntent.confirm(
                payment_intent.id,
                payment_method=payment_method,
            )
        except stripe.error.CardError as e:
            return JsonResponse({
                'status': 'failed',
                'stripeCode': e.code,
                'message': e.user_message
            })

        order = Order.objects.create(
            payment_intent_id=response.id,
            user=request.user,
            total_amount=request.POST['amount'],
        )

        for cart in request.user.carts.all():
            PurchaseHistory.objects.create(
                order=order,
                product=cart.product,
                qty=cart.qty,
                amount=cart.sum(),
            )

        request.user.carts.all().delete()

        return JsonResponse({'status': 'succeeded'})

core/views/product.py
from django.shortcuts import redirect, render
from django.views.generic import View

from core.models import Category, Product
from core.views.mixins import CategoryMixin, PaginationMixin


class ProductListView(CategoryMixin, PaginationMixin, View):
    def get(self, request, *args, **kwargs):
        category = Category.objects.get(pk=kwargs['pk'])
        # URLにorder_byパラメータがない場合は、idの昇順で並び替える
        products = category.products.all().order_by(request.GET.get('order_by', 'id'))
        context = {
            'category': category,
            'categories': self.get_categories(),  # 継承しているCategoryMixinのget_categoriesメソッドを実行
            **self.get_page_data(products)  # 継承しているPaginationMixinのget_page_dataメソッドを実行
        }
        return render(request, 'core/product/list.html', context)


class ProductDetailView(CategoryMixin, PaginationMixin, View):
    paginate_by = 2

    def get(self, request, *args, **kwargs):
        product = Product.objects.get(pk=kwargs['pk'])
        favorite_added = request.user.is_authenticated and request.user.favorites.filter(product=product).exists()
        context = {
            'product': product,
            'categories': self.get_categories(),  # 継承しているCategoryMixinのget_categoriesメソッドを実行
            'favorite_added': favorite_added,
            **self.get_page_data(product.reviews.all()),  # 継承しているPaginationMixinのget_page_dataメソッドを実行
        }
        return render(request, 'core/product/detail.html', context)


class ProductReviewView(View):
    def post(self, request, *args, **kwargs):
        product = Product.objects.get(pk=kwargs['pk'])
        product.reviews.create(
            user=request.user,
            score=request.POST['score'],
            body=request.POST['body']
        )
        return redirect('core:product_detail', product.pk)

core/views/search.py
from django.db.models import Avg, Q
from django.shortcuts import render
from django.views.generic import View

from core.models import Product
from core.views.mixins import CategoryMixin, PaginationMixin


class SearchView(CategoryMixin, PaginationMixin, View):
    def get(self, request, *args, **kwargs):
        # 検索用パラメータを表すQオブジェクト
        q = Q()
        for param_name, value in request.GET.items():
            if not value:
                continue
            if param_name == 'search_word':
                # プロダクト名に検索ワードが部分一致するか
                q &= Q(name__contains=value)
            elif param_name == 'category_name':
                # プロダクトのカテゴリーに一致するか
                q &= Q(category__name=value)
            elif param_name == 'star':
                # プロダクトのレビューの星がリクエスト値以上か
                q &= Q(star__gte=value)

        # valuesメソッドにより、プロダクトのpkでレコードをグループ化する。
        # annotateメソッドにより、レビューのスコアの平均値を求める。
        # Qオブジェクトにより、レコードをフィルターする。
        products = Product.objects.values('pk').annotate(star=Avg('reviews__score')).filter(q)

        # フィルター後にproductsに代入されているのはQuerySetではないので、フィルター後に残ったプロダクトのidにより、QuerySetを取得する
        products = Product.objects.filter(pk__in=[p['pk'] for p in products])

        context = {
            'categories': self.get_categories(),
            **self.get_page_data(products)
        }
        return render(request, 'core/search.html', context)

samazon_admin/views/product.py
from django.shortcuts import redirect, render
from django.views.generic import View

from core.models import Product
from core.views.mixins import PaginationMixin
from samazon_admin.forms import ProductCreateUpdateForm


class ProductListView(PaginationMixin, View):
    def get(self, request, *args, **kwargs):
        products = Product.objects.all()
        if 'keyword' in request.GET:
            products = products.filter(name__contains=request.GET['keyword'])
        products = products.order_by(request.GET.get('order_by', 'pk'))
        context = self.get_page_data(products)
        return render(request, 'samazon_admin/product/list.html', context)


class ProductCreateView(View):
    def get(self, request, *args, **kwargs):
        form = ProductCreateUpdateForm()
        return render(request, 'samazon_admin/product/create.html', {'form': form})

    def post(self, request, *args, **kwargs):
        # request.FILESにブラウザから送られてきた画像が入っている
        form = ProductCreateUpdateForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('samazon_admin:product_list')
        return render(request, 'samazon_admin/product/create.html', {'form': form})


class ProductDetailView(View):
    def get(self, request, *args, **kwargs):
        product = Product.objects.get(pk=kwargs['pk'])
        return render(request, 'samazon_admin/product/detail.html', {'product': product})


class ProductUpdateView(View):
    def get(self, request, *args, **kwargs):
        product = Product.objects.get(pk=kwargs['pk'])
        form = ProductCreateUpdateForm(instance=product)
        return render(request, 'samazon_admin/product/update.html', {'form': form})

    def post(self, request, *args, **kwargs):
        product = Product.objects.get(pk=kwargs['pk'])
        # request.FILESにブラウザから送られてきた画像が入っている
        form = ProductCreateUpdateForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            form.save()
            return redirect('samazon_admin:product_list')
        return render(request, 'samazon_admin/product/update.html', {'form': form})


class ProductDeleteView(View):
    def post(self, request, *args, **kwargs):
        product = Product.objects.get(pk=kwargs['pk'])
        product.delete()
        return redirect('samazon_admin:product_list')

core/templates/core/product/detail.html
{% extends 'core/base.html' %}

{% block content %}
  <div class="row">
    <div class="col-2">
      <!-- category.htmlを読み込む -->
      {% include 'core/category.html' %}
    </div>

    <div class="col-10">
      <a href="/">トップ</a> > <a href="#">{{ product.category.major_category.name }}</a> > <a href="{% url 'core:product_list' product.category.pk %}">{{ product.category.name }}</a>
      <br><br>
      <img src="{{ product.photo.url }}" width="500"><br>
      <h3>{{ product.name }}</h3>
      <p>{{ product.description }}</p>
      <h3>¥{{ product.price }}(税込)</h3>
      <!--
        ログインしている場合、user変数にはログインユーザーのインスタンスが代入されている。
        user変数は、djangoが自動的にテンプレートにレンダリングするので、viewから渡さなくても使用できる。
      -->
      {% if user.is_authenticated %}
        <form method="post" action="{% url 'core:cart_add' %}">
          {% csrf_token %}
          <input type="hidden" name="product_id" value="{{ product.pk }}">
          <label for="qty">数量: </label><input type="number" id="qty" name="qty" required><br>
          <button>カートに追加</button>
        </form>

        <br>

        <form method="post" action="{% url 'core:favorite_add_delete' %}">
          {% csrf_token %}
          <input type="hidden" name="product_id" value="{{ product.pk }}">
          <button class="favorite-btn">
            {% if favorite_added %}
              お気に入り削除
            {% else %}
              お気に入り追加
            {% endif %}
          </button>
        </form>

        <br>

        <h3>カスタマーレビュー</h3>

        {% if object_list %}
          {% for review in object_list %}
            <img src="https://images-fe.ssl-images-amazon.com/images/S/amazon-avatars-global/default._CR0,0,1024,1024_SX48_.png" class="" data-src="https://images-fe.ssl-images-amazon.com/images/S/amazon-avatars-global/default._CR0,0,1024,1024_SX48_.png">
            {{ review.user.username }}<br>
            {{ review.score_star }}<br>
            {{ review.created_at }}<br>
            {{ review.body }}<br><br>
          {% endfor %}
        {% else %}
          まだカスタマーレビューはありません
        {% endif %}

        {% if paginator.num_pages != 1 %}
          {% if page_obj.has_previous %}
            <a href="{% url 'core:product_detail' product.pk %}?page={{ page_obj.number|add:-1 }}">prev | </a>
          {% else %}
            <span>prev | </span>
          {% endif %}

          {% for page in paginator.page_range %}
            {% if page == page_obj.number %}
              <span>{{ page }} | </span>
            {% else %}
              <a href="{% url 'core:product_detail' product.pk %}?page={{ page }}">{{ page }} | </a>
            {% endif %}
          {% endfor %}

          {% if page_obj.has_next %}
            <a href="{% url 'core:product_detail' product.pk %}?page={{ page_obj.number|add:1 }}">next</a>
          {% else %}
            <span>next</span>
          {% endif %}
        {% endif %}

        <br><br>

        <form method="post" action="{% url 'core:product_review' product.pk %}">
          {% csrf_token %}
          <h5>評価</h5>
          <select name="score">
            <option value="5" class="review-score-color">★★★★★</option>
            <option value="4" class="review-score-color">★★★★</option>
            <option value="3" class="review-score-color">★★★</option>
            <option value="2" class="review-score-color">★★</option>
            <option value="1" class="review-score-color">★</option>
          </select>
          <h5>レビュー内容</h5>
          <textarea name="body"></textarea><br>
          <button>レビューを追加</button>
        </form>
      {% endif %}
    </div>
  </div>
{% endblock %}

core/templates/core/product/list.html
{% extends 'core/base.html' %}

{% block javascript %}
  <script>
    $(function () {
      // 並び替えセレクトボックスのオプションの値を１つ１つチェックする
      $('select[name=order_by] option').each(function () {
        // オプションの値が、直前に選択されたオプションの値であるか調べる
        if ($(this).val() === '{{ request.GET.order_by }}') {
          // オプションの値が、直前に選択されたオプションの値である場合、selected属性を追加する
          $(this).attr('selected', true);
        }
      });

      // 並び替えセレクトボックスの値が変更された際の処理
      $('select[name=order_by]').change(function () {
        // id="order-form"のformタグを取得
        const $form = $('#order-form');
        // formタグのaction属性のURLにリクエストする
        $form.submit();
      });

      // ページのリンクをクリックした際の処理
      $('.page').click(function () {
        // ページ番号を表すinputタグのvalue属性の値を、クリックされたページの値にする
        $('input[name=page]').val($(this).data('page'));
        // id="order-form"のformタグを取得
        const $form = $('#order-form');
        // formタグのaction属性のURLにリクエストする
        $form.submit();
        // aタグのリンクの効果を無効にする
        return false;
      });
    });
  </script>
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-2">
      {% include 'core/category.html' %}
    </div>

    <div class="col-10">
      <a href="/">トップ</a> > <a href="#">{{ category.major_category.name }}</a> > {{ category.name }}
      <br><br>
      <h3>{{ category.name }}の商品一覧{{ category.products.all.count }}件</h3>
      <form id="order-form" action="{% url 'core:product_list' category.pk %}">
        <input type="hidden" name="page" value="1">
        <select name="order_by">
          <option value="id">並び替え</option>
          <option value="price">価格の安い順</option>
          <option value="-price">価格の高い順</option>
          <option value="created_at">出品の古い順</option>
          <option value="-created_at">出品の新しい順</option>
        </select>
      </form>
      <br><br>

      <div class="d-flex flex-wrap">
        <!-- object_listには、対象のページのproductインスタンスが代入されている -->
        {% for product in object_list %}
          <div class="mr-4 mb-4">
            <a href="{% url 'core:product_detail' product.pk %}">
              <img src="{{ product.photo.url }}" width="300"><br>
            </a>
            {{ product.name }}<br>
            ¥{{ product.price }}
          </div>
        {% endfor %}
      </div>

      {% if paginator.num_pages != 1 %}
        {% if page_obj.has_previous %}
          <a class="page" href="" data-page="{{ page_obj.number|add:-1 }}">prev | </a>
        {% else %}
          <span>prev | </span>
        {% endif %}

        {% for page in paginator.page_range %}
          {% if page == page_obj.number %}
            <span>{{ page }} | </span>
          {% else %}
            <a class="page" href="" data-page="{{ page }}">{{ page }} | </a>
          {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
          <a class="page" href="" data-page="{{ page_obj.number|add:1 }}">next</a>
        {% else %}
          <span>next</span>
        {% endif %}
      {% endif %}
    </div>
  </div>
{% endblock %}